const CONSTANTES = {
  GET_ARTICULOS: 'GET_ARTICULOS',
  GET_ARTICULO_DESTACADO: 'GET_ARTICULO_DESTACADO',
  GET_ARTICULOS_CATEGORIA: 'GET_ARTICULOS_CATEGORIA',
  GET_ARTICULO_SLUG: 'GET_ARTICULO_SLUG',
  GET_ARTICULO: 'GET_ARTICULO',
  AGREGAR_ARTICULOS_STORE: 'AGREGAR_ARTICULOS_STORE',
  GET_EMPRESA: 'GET_EMPRESA',
  GET_EMPRESA_INFO: 'GET_EMPRESA_INFO',
  GET_CATEGORIAS_EMPRESA: 'GET_CATEGORIAS_EMPRESA',
};

export default CONSTANTES;
